<?php

namespace Database\Seeders;

use App\Models\Office;
use Illuminate\Database\Seeder;

class OfficeSeeder extends Seeder
{
    public function run(): void
    {
        $offices = [
            // ── Regular Bureaus ───────────────────────────────────────────────
            [
                'name' => 'თბილისის იურიდიული დახმარების ბიურო',
                'type' => 'bureau', 'region' => 'თბილისი', 'city' => 'თბილისი',
                'head' => 'გიორგი ჩაკვეტაძე',
                'address' => 'თამარ მეფის გამზ. №14, თბილისი 0112, საქართველო',
                'phone' => '+995 032 2920055', 'mobile' => '+995 (595) 364410',
                'email' => 'gchakvetadze@legalaid.ge',
                'working_hours' => 'ორ-პარ: 09:00-18:00',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 1,
            ],
            [
                'name' => 'მცხეთის იურიდიული დახმარების ბიურო',
                'type' => 'bureau', 'region' => 'მცხეთა-მთიანეთი', 'city' => 'მცხეთა',
                'head' => 'ალუდა ბუჩუკური',
                'address' => 'მცხეთა, დ. აღმაშენებლის ქ. №51',
                'phone' => '+995 (32) 2513873', 'mobile' => '+995 (595) 901705',
                'email' => 'abuchukuri@legalaid.ge',
                'working_hours' => 'ორ-პარ: 09:00-18:00',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 2,
            ],
            [
                'name' => 'თელავის იურიდიული დახმარების ბიურო',
                'type' => 'bureau', 'region' => 'კახეთი', 'city' => 'თელავი',
                'head' => 'გია ფარადაშვილი',
                'address' => 'თელავი, ვარდოშვილის ქ. №7',
                'phone' => '+995 (350) 271538', 'mobile' => '+995 595 90 17 56',
                'email' => 'gfaradashvili@legalaid.ge',
                'working_hours' => 'ორ-პარ: 09:00-18:00',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 3,
            ],
            [
                'name' => 'სიღნაღის იურიდიული დახმარების ბიურო',
                'type' => 'bureau', 'region' => 'კახეთი', 'city' => 'სიღნაღი',
                'head' => 'თამაზ გურაშვილი',
                'address' => 'სიღნაღი, აღმაშენებლის ქ. №7',
                'phone' => '+995 (355) 231082', 'mobile' => '+995 (599) 937973',
                'email' => 'tgurashvili@legalaid.ge',
                'working_hours' => 'ორ-პარ: 09:00-18:00',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 4,
            ],
            [
                'name' => 'რუსთავის იურიდიული დახმარების ბიურო',
                'type' => 'bureau', 'region' => 'ქვემო ქართლი', 'city' => 'რუსთავი',
                'head' => 'მაკა რევია',
                'address' => 'რუსთავი, ბოსტანქალაქის ქ. №6',
                'phone' => '+995 (341) 241425', 'mobile' => '+995 (599) 091 552',
                'email' => 'mrevia@legalaid.ge',
                'working_hours' => 'ორ-პარ: 09:00-18:00',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 5,
            ],
            [
                'name' => 'გორის იურიდიული დახმარების ბიურო',
                'type' => 'bureau', 'region' => 'შიდა ქართლი', 'city' => 'გორი',
                'head' => 'გიორგი ჯეირანაშვილი',
                'address' => 'გორი, სამეფოს ქ. №54',
                'phone' => '+995 (370) 279556', 'mobile' => '+995 (595) 901704',
                'email' => 'gjeiranashvili@legalaid.ge',
                'working_hours' => 'ორ-პარ: 09:00-18:00',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 6,
            ],
            [
                'name' => 'ახალციხის იურიდიული დახმარების ბიურო',
                'type' => 'bureau', 'region' => 'სამცხე-ჯავახეთი', 'city' => 'ახალციხე',
                'head' => 'დავით ზარიძე',
                'address' => 'ახალციხე, თაბუკაშვილის ქ.№17',
                'phone' => '+995 (362) 220735', 'mobile' => '+995 (599) 722176',
                'email' => 'dzaridze@legalaid.ge',
                'working_hours' => 'ორ-პარ: 09:00-18:00',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 7,
            ],
            [
                'name' => 'ზესტაფონის იურიდიული დახმარების ბიურო',
                'type' => 'bureau', 'region' => 'იმერეთი', 'city' => 'ზესტაფონი',
                'head' => 'გელა ბერაძე',
                'address' => 'ზესტაფონი, წერეთლის ქ. №11',
                'phone' => '+995 (492) 253637', 'mobile' => '+995 (595) 364441',
                'email' => 'gberadze@legalaid.ge',
                'working_hours' => 'ორ-პარ: 09:00-18:00',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 8,
            ],
            [
                'name' => 'ქუთაისის იურიდიული დახმარების ბიურო',
                'type' => 'bureau', 'region' => 'იმერეთი', 'city' => 'ქუთაისი',
                'head' => 'ესმა ნორაკია',
                'address' => 'ქუთაისი, სადგურის მოედანი №3ა',
                'phone' => '+995 (431) 253411; 253412', 'mobile' => '+995 (595) 901700',
                'email' => 'enorakia@legalaid.ge',
                'working_hours' => 'ორ-პარ: 09:00-18:00',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 9,
            ],
            [
                'name' => 'ზუგდიდის იურიდიული დახმარების ბიურო',
                'type' => 'bureau', 'region' => 'სამეგრელო-ზემო სვანეთი', 'city' => 'ზუგდიდი',
                'head' => 'რომან კეიდია',
                'address' => 'ზუგდიდი, ნარმანიას ქ. №3',
                'phone' => '+995 (415) 220040', 'mobile' => '+995 (595) 901702',
                'email' => 'rkeidia@legalaid.ge',
                'working_hours' => 'ორ-პარ: 09:00-18:00',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 10,
            ],
            [
                'name' => 'ფოთის იურიდიული დახმარების ბიურო',
                'type' => 'bureau', 'region' => 'სამეგრელო-ზემო სვანეთი', 'city' => 'ფოთი',
                'head' => 'ნათია ბოჯგუა',
                'address' => 'ფოთი, დავით აღმაშენებლის. №9',
                'phone' => '+995 (493) 223234', 'mobile' => '+995 (595) 901703',
                'email' => 'nbodjgua@legalaid.ge',
                'working_hours' => 'ორ-პარ: 09:00-18:00',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 11,
            ],
            [
                'name' => 'ბათუმის იურიდიული დახმარების ბიურო',
                'type' => 'bureau', 'region' => 'აჭარა', 'city' => 'ბათუმი',
                'head' => 'იამზე ზანდარაძე',
                'address' => 'ბათუმი, პუშკინის №145',
                'phone' => null, 'mobile' => '+995 (595) 901701',
                'email' => 'izandaradze@legalaid.ge',
                'working_hours' => 'ორ-პარ: 09:00-18:00',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 12,
            ],
            [
                'name' => 'ოზურგეთის იურიდიული დახმარების ბიურო',
                'type' => 'bureau', 'region' => 'გურია', 'city' => 'ოზურგეთი',
                'head' => 'ცირა მდინარაძე',
                'address' => 'ოზურგეთი, ილია ჭავჭავაძის ქ. №12',
                'phone' => '+995 (496) 275992', 'mobile' => '+995 (595) 308850',
                'email' => 'tmdinaradze@legalaid.ge',
                'working_hours' => 'ორ-პარ: 09:00-18:00',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 13,
            ],
            [
                'name' => 'გურჯაანის იურიდიული დახმარების ბიურო',
                'type' => 'bureau', 'region' => 'კახეთი', 'city' => 'გურჯაანი',
                'head' => 'ლიანა ჭუნიაშვილი',
                'address' => 'გურჯაანი, ნონეშვილის ქ. #4',
                'phone' => null, 'mobile' => '+995 557230027',
                'email' => 'ggiashvili@legalaid.ge',
                'working_hours' => 'ორ-პარ: 09:00-18:00',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 14,
            ],
            [
                'name' => 'ბოლნისის იურიდიული დახმარების ბიურო',
                'type' => 'bureau', 'region' => 'ქვემო ქართლი', 'city' => 'ბოლნისი',
                'head' => null,
                'address' => 'ბოლნისი, სულხან-საბა ორბელიანის # 106',
                'phone' => null, 'mobile' => '+995 551 42 44 00',
                'email' => 'laludauri@legalaid.ge',
                'working_hours' => 'ორ-პარ: 09:00-18:00',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 15,
            ],
            // ── Specialized Bureaus ───────────────────────────────────────────
            [
                'name' => 'სპეციალიზებული საქმეთა ბიურო',
                'type' => 'bureau', 'region' => 'თბილისი', 'city' => 'თბილისი',
                'head' => 'თეონა კვერნაძე',
                'address' => 'თბილისი, ლუარსაბ ანდრონიკაშვილის ქ. 1 ა, მე-2 სართ.',
                'phone' => '+995 (32) 2954474', 'mobile' => '+995 591041446',
                'email' => 'tkvernadze@legalaid.ge',
                'working_hours' => 'ორ-პარ: 09:00-18:00',
                'is_specialized' => true, 'is_active' => true, 'sort_order' => 16,
            ],
            [
                'name' => 'აღმოსავლეთ საქართველოს განსაკუთრებული საქმეთა ბიურო',
                'type' => 'bureau', 'region' => 'თბილისი', 'city' => 'თბილისი',
                'head' => 'სულხან კომახიძე',
                'address' => 'თბილისი, თამარ მეფის ქ. # 14, მე3 სართ',
                'phone' => null, 'mobile' => '+995 (595) 364411',
                'email' => 'skomakhidze@legalaid.ge',
                'working_hours' => 'ორ-პარ: 09:00-18:00',
                'is_specialized' => true, 'is_active' => true, 'sort_order' => 17,
            ],
            [
                'name' => 'დასავლეთ საქართველოს განსაკუთრებული საქმეთა ბიურო',
                'type' => 'bureau', 'region' => 'იმერეთი', 'city' => 'ქუთაისი',
                'head' => 'გელა სიორდია',
                'address' => 'ქუთაისი, სადგურის მოედანი №3ა',
                'phone' => '+995 (431) 253411; 253412', 'mobile' => '+995 595 901700',
                'email' => 'gsiordia@legalaid.ge',
                'working_hours' => 'ორ-პარ: 09:00-18:00',
                'is_specialized' => true, 'is_active' => true, 'sort_order' => 18,
            ],
            // ── Consultation Centers ──────────────────────────────────────────
            [
                'name' => 'ამბროლაურის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'რაჭა-ლეჩხუმი', 'city' => 'ამბროლაური',
                'head' => 'თეა ჩიკვაიძე',
                'address' => 'ამბროლაური, აღმაშენებლის ქ. №24',
                'phone' => null, 'mobile' => '+995 (595) 308847',
                'email' => 'tchikvaidze@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 20,
            ],
            [
                'name' => 'მესტიის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'სამეგრელო-ზემო სვანეთი', 'city' => 'მესტია',
                'head' => 'ავთანდილ ჯაფარიძე',
                'address' => 'მესტია, სეტის მოედანი №19',
                'phone' => null, 'mobile' => '+995 (551) 201947; +995 (599) 294477',
                'email' => 'ajaparidze@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 21,
            ],
            [
                'name' => 'საჩხერის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'იმერეთი', 'city' => 'საჩხერე',
                'head' => 'სალომე გიორგაძე',
                'address' => 'საჩხერე, თავისუფლების ქ.№4',
                'phone' => null, 'mobile' => '+995 (558) 194637',
                'email' => 'sgiorgiadze@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 22,
            ],
            [
                'name' => 'ახალქალაქის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'სამცხე-ჯავახეთი', 'city' => 'ახალქალაქი',
                'head' => 'ინგა გვარამაძე',
                'address' => 'ახალქალაქი, თამარ მეფის №44',
                'phone' => null, 'mobile' => '+995 (599)358585',
                'email' => 'igvaramadze@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 23,
            ],
            [
                'name' => 'წალკის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'ქვემო ქართლი', 'city' => 'წალკა',
                'head' => 'დავით გოგიჩაიშვილი',
                'address' => 'წალკა, არისტოტელეს №22',
                'phone' => null, 'mobile' => '+995 (599) 090091',
                'email' => 'dgogichaishvili@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 24,
            ],
            [
                'name' => 'მარნეულის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'ქვემო ქართლი', 'city' => 'მარნეული',
                'head' => 'ლალი ალუდაური',
                'address' => 'მარნეული, რუსთაველის №73',
                'phone' => null, 'mobile' => '+995 (551) 424400',
                'email' => 'laludauri@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 25,
            ],
            [
                'name' => 'დუისის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'კახეთი', 'city' => 'ახმეთა',
                'head' => 'ნუნუ გელდიაშვილი',
                'address' => 'ახმეტის მუნიციპალიტეტის სოფელი დუისი',
                'phone' => null, 'mobile' => '+995 (599) 161076',
                'email' => 'ngeldiashvili@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 26,
            ],
            [
                'name' => 'შუახევის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'აჭარა', 'city' => 'შუახევი',
                'head' => 'ნინო შარაშიძე',
                'address' => 'დაბა შუახევი, ხიმშიაშვილის ქ # 2',
                'phone' => null, 'mobile' => '+995 595 91 00 34',
                'email' => 'nsharashidze@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 27,
            ],
            [
                'name' => 'ცაგერის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'რაჭა-ლეჩხუმი', 'city' => 'ცაგერი',
                'head' => 'ნინო ურთმელიძე',
                'address' => 'ცაგერი, რუსთაველის ქუჩა # 65',
                'phone' => null, 'mobile' => '+995 (595) 097660',
                'email' => 'nurtmelidze@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 28,
            ],
            [
                'name' => 'ჭიათურის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'იმერეთი', 'city' => 'ჭიათურა',
                'head' => 'სალომე გიორგაძე',
                'address' => 'ჭიათურა, ნინოშვილის ქუჩა #5',
                'phone' => null, 'mobile' => '+995 (558) 194637',
                'email' => 'sgiorgadze@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 29,
            ],
            [
                'name' => 'ლაგოდეხის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'კახეთი', 'city' => 'ლაგოდეხი',
                'head' => 'ნანა ბოლაშვილი',
                'address' => 'ლაგოდეხი, მერაბ კოსტავას ქუჩა # 1',
                'phone' => null, 'mobile' => '+995 551 210 176',
                'email' => 'nbolashvili@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 30,
            ],
            [
                'name' => 'დუშეთის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'მცხეთა-მთიანეთი', 'city' => 'დუშეთი',
                'head' => 'ირინა ბარბაქაძე',
                'address' => 'დუშეთი, დავით აღმაშენებლის ქუჩა #27',
                'phone' => null, 'mobile' => '+995 (595) 337 177',
                'email' => 'ibarbakadze@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 31,
            ],
            [
                'name' => 'დმანისის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'ქვემო ქართლი', 'city' => 'დმანისი',
                'head' => 'ლალი ალუდაური',
                'address' => 'დმანისი, წმინდა ნინოს ქუჩა #39',
                'phone' => null, 'mobile' => '+995 (551) 424 400',
                'email' => 'laludauri@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 32,
            ],
            [
                'name' => 'ყვარლის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'კახეთი', 'city' => 'ყვარელი',
                'head' => 'გურანდა გიაშვილი',
                'address' => 'ყვარელი, კუდიგორის ქუჩა # 2',
                'phone' => null, 'mobile' => '+995 557230027',
                'email' => 'ggiasdhvili@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 33,
            ],
            [
                'name' => 'ბაღდათის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'იმერეთი', 'city' => 'ბაღდათი',
                'head' => 'თინათინ შავრეშიანი',
                'address' => 'ბაღდათი, შოთა რუსთველის ქ.# 21',
                'phone' => null, 'mobile' => '+995 57714 88 78',
                'email' => 'tshavreshiani@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 34,
            ],
            [
                'name' => 'წყალტუბოს საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'იმერეთი', 'city' => 'წყალტუბო',
                'head' => 'თინათინ შავრეშიანი',
                'address' => 'წყალტუბო, შოთა რუსთველის ქ. # 25',
                'phone' => '+995 14 88 78', 'mobile' => null,
                'email' => 'tshavreshiani@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 35,
            ],
            [
                'name' => 'ხულოს საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'აჭარა', 'city' => 'ხულო',
                'head' => 'ნინო შარაშიძე',
                'address' => 'ხულო, დავით აღმაშენებლის ქ. # 3',
                'phone' => '+995 595 91 00 34', 'mobile' => null,
                'email' => 'nsharashidze@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 36,
            ],
            [
                'name' => 'ქედის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'აჭარა', 'city' => 'ქედა',
                'head' => 'ნინო შარაშიძე',
                'address' => 'ქედა, 26 მაისის ქ. # 2',
                'phone' => '+995 595 91 00 34', 'mobile' => null,
                'email' => 'nsharashidze@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 37,
            ],
            [
                'name' => 'ქობულეთის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'აჭარა', 'city' => 'ქობულეთი',
                'head' => 'ნინო შარაშიძე',
                'address' => 'ქობულეთი, თავისუფლების ქ. # 13',
                'phone' => '+995 595 91 00 34', 'mobile' => null,
                'email' => 'nsharashidze@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 38,
            ],
            [
                'name' => 'აბაშის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'სამეგრელო-ზემო სვანეთი', 'city' => 'აბაშა',
                'head' => 'მაია რობაქიძე',
                'address' => 'აბაშა, უჩა კაჭარავას ქ.# 1',
                'phone' => '+995 599 98 42 99', 'mobile' => null,
                'email' => 'mrobakidze@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 39,
            ],
            [
                'name' => 'მარტვილის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'სამეგრელო-ზემო სვანეთი', 'city' => 'მარტვილი',
                'head' => 'მაია რობაქიძე',
                'address' => 'მარტვილი, თავისუფლების ქ # .10',
                'phone' => '+995 599 98 42 99', 'mobile' => null,
                'email' => 'mrobakidze@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 40,
            ],
            [
                'name' => 'ჩხოროწყუს საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'სამეგრელო-ზემო სვანეთი', 'city' => 'ჩხოროწყუ',
                'head' => 'ნინო ხარჩილავა',
                'address' => 'ჩხოროწყუ, დავით აღმაშენებლის ქ # .1',
                'phone' => '+995 555 41 88 32', 'mobile' => null,
                'email' => 'nkharchilava@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 41,
            ],
            [
                'name' => 'წალენჯიხის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'სამეგრელო-ზემო სვანეთი', 'city' => 'წალენჯიხა',
                'head' => 'ნინო ხარჩილავა',
                'address' => 'წალენჯიხა, სალიას ქ # 5',
                'phone' => '+995 555 41 88 32', 'mobile' => null,
                'email' => 'nkharchilava@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 42,
            ],
            [
                'name' => 'სენაკის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'სამეგრელო-ზემო სვანეთი', 'city' => 'სენაკი',
                'head' => 'მაია რობაქიძე',
                'address' => 'სენაკი, აკაკი წერეთლის ქ # 1',
                'phone' => '+995 599 98 42 99', 'mobile' => null,
                'email' => 'mrobakidze@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 43,
            ],
            [
                'name' => 'ხობის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'სამეგრელო-ზემო სვანეთი', 'city' => 'ხობი',
                'head' => 'სალომე ჯანჯღავა',
                'address' => 'ხობი, ცოტნე დადიანის ქ # 185',
                'phone' => '+995 591 911 304', 'mobile' => null,
                'email' => 'sjanjgava@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 44,
            ],
            [
                'name' => 'დედოფლისწყაროს საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'კახეთი', 'city' => 'დედოფლისწყარო',
                'head' => 'ნანა ბოლაშვილი',
                'address' => 'დედოფლისწყარო, მ.კოსტავას ქ # 44',
                'phone' => null, 'mobile' => '+995 551 210 176',
                'email' => 'nbolashvili@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 45,
            ],
            [
                'name' => 'ახმეტის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'კახეთი', 'city' => 'ახმეტა',
                'head' => 'ნუნუ გელდიაშვილი',
                'address' => 'ახმეტა, ბ. ჩოლოყაშვილის ქ. # 50',
                'phone' => null, 'mobile' => '+995 (599) 161076',
                'email' => 'ngeldiashvili@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 46,
            ],
            [
                'name' => 'ლენტეხის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'რაჭა-ლეჩხუმი', 'city' => 'ლენტეხი',
                'head' => 'ნინო ურთმელიძე',
                'address' => 'ლენტეხი, თამარ მეფის ქ. # 24',
                'phone' => null, 'mobile' => '+995 (595) 09 76 60',
                'email' => 'nurtmelidze@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 47,
            ],
            [
                'name' => 'ონის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'რაჭა-ლეჩხუმი', 'city' => 'ონი',
                'head' => 'თეა ჩიკვაიძე',
                'address' => 'ონი, სოფ. შეუბანი',
                'phone' => null, 'mobile' => '+995 595 30 88 47',
                'email' => 'tchikvaidze@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 48,
            ],
            [
                'name' => 'ხაშურის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'შიდა ქართლი', 'city' => 'ხაშური',
                'head' => 'მანანა გელაშვილი',
                'address' => 'ხაშური, მ.კოსტავას ქ.#11',
                'phone' => null, 'mobile' => '+995 598 60 90 34',
                'email' => 'mgelashvili@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 49,
            ],
            [
                'name' => 'ხონის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'იმერეთი', 'city' => 'ხონი',
                'head' => 'ესმა ნორაკია',
                'address' => 'ხონი, პოლიკარპე კაკაბაძის #17',
                'phone' => null, 'mobile' => '+995 (595) 901700',
                'email' => 'enorakia@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 50,
            ],
            [
                'name' => 'ლანჩხუთის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'გურია', 'city' => 'ლანჩხუთი',
                'head' => 'მარინე კიკნაძე',
                'address' => 'ლანჩხუთი, ნინოშვილის #21',
                'phone' => null, 'mobile' => '+995 577148890',
                'email' => 'mkiknadze@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 51,
            ],
            [
                'name' => 'ხარაგაულის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'იმერეთი', 'city' => 'ხარაგაული',
                'head' => 'თეა ჯანგიანი',
                'address' => 'ხარაგაული, 9 აპრილის ქ. #15',
                'phone' => null, 'mobile' => '+995 595 10 30 58',
                'email' => 'tjangiani@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 52,
            ],
            [
                'name' => 'სამტრედიის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'იმერეთი', 'city' => 'სამტრედია',
                'head' => 'მამუკა მაჩიტიძე',
                'address' => 'სამტრედია, რესპუბლიკის ქ. #6',
                'phone' => null, 'mobile' => '+995 595 58 90 57',
                'email' => 'mmachitidze@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 53,
            ],
            [
                'name' => 'ვანის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'იმერეთი', 'city' => 'ვანი',
                'head' => 'ესმა ნორაკია',
                'address' => 'ვანი, თავისუფლების ქ. #65',
                'phone' => null, 'mobile' => '+995 (595) 901700',
                'email' => 'enorakia@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 54,
            ],
            [
                'name' => 'ტყიბულის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'იმერეთი', 'city' => 'ტყიბული',
                'head' => 'მარიამ ოყრეშიძე',
                'address' => 'ტყიბული, კ.ლომაძის მოედანი#3',
                'phone' => null, 'mobile' => '+995 599 146 147',
                'email' => 'mokhreshidze@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 55,
            ],
            [
                'name' => 'ადიგენის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'სამცხე-ჯავახეთი', 'city' => 'ადიგენი',
                'head' => 'ლაშა ჯაფიაშვილი',
                'address' => 'ადიგენი, არტემ ბალახაშვილის ქ.#19',
                'phone' => null, 'mobile' => '+995 595 088 716',
                'email' => 'ljapiashvili@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 56,
            ],
            [
                'name' => 'რუხის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'სამეგრელო-ზემო სვანეთი', 'city' => 'ზუგდიდი',
                'head' => 'ნინო მინჯია',
                'address' => 'ზუგდიდის მუნიციპალიტეტის სოფელი რუხი',
                'phone' => null, 'mobile' => '+995 595 90 17 24',
                'email' => 'nminjia@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 57,
            ],
            [
                'name' => 'ქარელის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'შიდა ქართლი', 'city' => 'ქარელი',
                'head' => 'ნინო მასურაშვილი',
                'address' => 'ქარელი, თამარ მეფის ქ. #24',
                'phone' => null, 'mobile' => '+995 599 74 35 04',
                'email' => 'nmasurashvili@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 58,
            ],
            [
                'name' => 'თიანეთის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'მცხეთა-მთიანეთი', 'city' => 'თიანეთი',
                'head' => 'ირინა ბარბაქაძე',
                'address' => 'თიანეთი, რუსთაველის ქუჩა',
                'phone' => null, 'mobile' => '+995 595 33 71 77',
                'email' => 'ibarbakadze@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 59,
            ],
            [
                'name' => 'გარდაბნის საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'ქვემო ქართლი', 'city' => 'გარდაბანი',
                'head' => 'ლალი ალუდაური',
                'address' => 'გარდაბანი, დავით აღმაშენებლის ქ. # 127',
                'phone' => null, 'mobile' => '+995 551 42 44 00',
                'email' => 'laludauri@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 60,
            ],
            [
                'name' => 'თეთრიწყაროს საკონსულტაციო ცენტრი',
                'type' => 'consultation_center', 'region' => 'ქვემო ქართლი', 'city' => 'თეთრიწყარო',
                'head' => 'ლალი ალუდაური',
                'address' => 'თეთრიწყარო, თამარ მეფის ქ, # 34',
                'phone' => null, 'mobile' => '+995 551 42 44 00',
                'email' => 'laludauri@legalaid.ge',
                'is_specialized' => false, 'is_active' => true, 'sort_order' => 61,
            ],
        ];

        foreach ($offices as $data) {
            Office::updateOrCreate(
                ['name' => $data['name']],
                $data
            );
        }

        $bureaus        = collect($offices)->where('type', 'bureau')->count();
        $centers        = collect($offices)->where('type', 'consultation_center')->count();
        $specialized    = collect($offices)->where('is_specialized', true)->count();

        $this->command->info("✅ Offices seeded: {$bureaus} bureaus ({$specialized} specialized) + {$centers} consultation centers. Total: " . count($offices));
    }
}
