<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('posts', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('legacy_id')->nullable()->index();
            $table->string('title');
            $table->string('slug')->unique();
            $table->longText('content');
            $table->text('excerpt')->nullable();

            // Featured image paths (generated by ImageService)
            $table->string('featured_image')->nullable();
            $table->string('featured_image_thumbnail')->nullable();
            $table->string('featured_image_popup')->nullable();
            $table->string('featured_image_single')->nullable();
            $table->string('featured_image_webp')->nullable();
            $table->string('featured_image_thumbnail_webp')->nullable();

            $table->string('status')->default('published'); // draft, published, scheduled
            $table->timestamp('published_at')->nullable();
            $table->boolean('is_featured')->default(false);

            $table->string('seo_title')->nullable();
            $table->text('seo_description')->nullable();
            $table->string('og_image')->nullable();

            $table->string('author')->nullable();
            $table->string('source_url')->nullable();

            $table->json('extra_images')->nullable(); // additional gallery images
            $table->integer('views')->default(0);
            $table->integer('sort_order')->default(0);

            $table->timestamps();
            $table->softDeletes();
        });

        Schema::create('category_post', function (Blueprint $table) {
            $table->id();
            $table->foreignId('post_id')->constrained()->cascadeOnDelete();
            $table->foreignId('category_id')->constrained()->cascadeOnDelete();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('category_post');
        Schema::dropIfExists('posts');
    }
};
