<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('journals', function (Blueprint $table) {
            $table->id();
            $table->string('title');
            $table->string('slug')->unique();
            $table->text('description')->nullable();
            $table->string('cover_image')->nullable();
            $table->string('cover_image_thumbnail')->nullable();
            $table->string('file_path')->nullable();
            $table->string('year')->nullable();
            $table->string('volume')->nullable();
            $table->string('issue_number')->nullable();
            $table->date('published_at')->nullable();
            $table->boolean('is_active')->default(true);
            $table->integer('sort_order')->default(0);
            $table->integer('download_count')->default(0);
            $table->timestamps();
            $table->softDeletes();
        });

        Schema::create('vacancies', function (Blueprint $table) {
            $table->id();
            $table->string('title');
            $table->string('slug')->unique();
            $table->longText('content');
            $table->text('excerpt')->nullable();
            $table->string('department')->nullable();
            $table->string('location')->nullable();
            $table->string('type')->default('full_time'); // full_time, part_time, contract, internship
            $table->string('status')->default('open'); // open, closed, draft
            $table->date('deadline')->nullable();
            $table->boolean('is_active')->default(true);
            $table->integer('sort_order')->default(0);
            $table->json('requirements')->nullable();
            $table->json('responsibilities')->nullable();
            $table->string('contact_email')->nullable();
            $table->string('application_url')->nullable();
            $table->timestamps();
            $table->softDeletes();
        });

        Schema::create('videos', function (Blueprint $table) {
            $table->id();
            $table->string('title');
            $table->text('description')->nullable();
            $table->string('youtube_id')->nullable();
            $table->string('youtube_url')->nullable();
            $table->string('thumbnail')->nullable();
            $table->string('category')->nullable();
            $table->boolean('is_active')->default(true);
            $table->date('published_at')->nullable();
            $table->integer('sort_order')->default(0);
            $table->timestamps();
        });

        Schema::create('projects', function (Blueprint $table) {
            $table->id();
            $table->string('title');
            $table->string('slug')->unique();
            $table->string('subtitle')->nullable();
            $table->text('description')->nullable();
            $table->longText('content')->nullable();
            // Image variants (generated by ImageService)
            $table->string('featured_image')->nullable();
            $table->string('featured_image_thumbnail')->nullable();
            $table->string('featured_image_popup')->nullable();
            $table->string('featured_image_webp')->nullable();
            $table->string('featured_image_thumbnail_webp')->nullable();
            $table->string('partner')->nullable();
            $table->string('donor')->nullable();
            $table->string('external_url')->nullable();
            $table->date('start_date')->nullable();
            $table->date('end_date')->nullable();
            $table->string('status')->default('active'); // active, completed, planned
            $table->boolean('is_active')->default(true);
            $table->boolean('is_featured')->default(false);
            $table->integer('sort_order')->default(0);
            $table->timestamps();
            $table->softDeletes();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('projects');
        Schema::dropIfExists('videos');
        Schema::dropIfExists('vacancies');
        Schema::dropIfExists('journals');
    }
};
